
package proyectobancoplus.Presentacion;

/**
 *
 * @author Cesar Luna
 */
public class AltaCuentaForm extends javax.swing.JFrame {

    /**
     * Creates new form AltaCuentaForm
     */
    public AltaCuentaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SaldoInicial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumeroCuenta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nuevo numero de cuenta");

        txtNumeroCuenta.setColumns(20);
        txtNumeroCuenta.setRows(5);
        jScrollPane1.setViewportView(txtNumeroCuenta);

        jLabel2.setText("Saldo inicial:");

        btnCrearCuenta.setText("Crear cuenta nueva");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrearCuenta)
                                .addGap(48, 48, 48)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCuenta)
                    .addComponent(jButton2))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed

        try {
            String textoSaldo = SaldoInicial.getText(); 
            if (textoSaldo.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Entrada de datos invalida\nIngrese numeros para indicar saldo");
                return;
            }
        Float saldoIngresado = Float.parseFloat(textoSaldo);
        proyectobancoplus.Entidades.Cliente clienteMientras = new proyectobancoplus.Entidades.Cliente();
        clienteMientras.setIdCliente(1);
        Integer numeroDePantalla = Integer.parseInt(txtNumeroCuenta.getText());
        proyectobancoplus.dtos.NuevoCuentaDTO dto = new proyectobancoplus.dtos.NuevoCuentaDTO(numeroDePantalla, saldoIngresado, null, clienteMientras);
        proyectobancoplus.Persistencia.ICuentaDAO dao = new proyectobancoplus.Persistencia.CuentasDAO();
        proyectobancoplus.Negocio.CuentaBO bo = new proyectobancoplus.Negocio.CuentaBO(dao);
        proyectobancoplus.Entidades.Cuenta nuevaCuenta = bo.crearCuenta(dto);        
 
        txtNumeroCuenta.setText(String.valueOf(nuevaCuenta.getNumCuenta()));
        javax.swing.JOptionPane.showMessageDialog(this, "¡Cuenta creada exitosamente!\nTu número es: " + nuevaCuenta.getNumCuenta());
        this.dispose(); 

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Entrada de datos invalida\nIngrese numeros para indicar saldo");
        } catch (proyectobancoplus.Negocio.NegocioException e) {        
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (proyectobancoplus.Persistencia.PersistenciaException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCuentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaCuentaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SaldoInicial;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
