
package proyectobancoplus.Presentacion;

import javax.swing.JOptionPane;
import proyectobancoplus.Entidades.Cliente;
import proyectobancoplus.Negocio.ITransferencias;

/**
 *
 * @author melis
 */
public class MenuForm extends javax.swing.JFrame {

    private Cliente clienteA;
    private ITransferencias transferenciaBO;

    /**
     * Creates new form MenuForm
     */
    public MenuForm(Cliente cliente, ITransferencias trBO) {
        this.clienteA = cliente;
        this.transferenciaBO = trBO;
        initComponents();
        setTitle("Menu Principal----BancoPlus");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarSesion = new javax.swing.JButton();
        btnMisCuentas = new javax.swing.JButton();
        btnTrasferencias = new javax.swing.JButton();
        btnRetiroSinCuenta = new javax.swing.JButton();
        btnCrearMasCuentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnMisCuentas.setText("Mis cuentas");
        btnMisCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisCuentasActionPerformed(evt);
            }
        });

        btnTrasferencias.setText("Transferir");
        btnTrasferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasferenciasActionPerformed(evt);
            }
        });

        btnRetiroSinCuenta.setText("Retirar sin cuenta");
        btnRetiroSinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroSinCuentaActionPerformed(evt);
            }
        });

        btnCrearMasCuentas.setText("Crear nueva Cuenta");
        btnCrearMasCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMasCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnCrearMasCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMisCuentas)
                            .addComponent(btnTrasferencias)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnRetiroSinCuenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMasCuentas)
                    .addComponent(btnCerrarSesion))
                .addGap(27, 27, 27)
                .addComponent(btnMisCuentas)
                .addGap(18, 18, 18)
                .addComponent(btnTrasferencias)
                .addGap(18, 18, 18)
                .addComponent(btnRetiroSinCuenta)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnCrearMasCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMasCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMasCuentasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
       int confirm = JOptionPane.showConfirmDialog(this, "cerrar la sesion?","Salir",JOptionPane.YES_NO_OPTION);
        if (confirm==JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMisCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisCuentasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Se estan busvando las cuentas");
    }//GEN-LAST:event_btnMisCuentasActionPerformed

    private void btnTrasferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasferenciasActionPerformed
        // TODO add your handling code here:;
        TransferenciaForm pantallaTransferencias = new TransferenciaForm(transferenciaBO,clienteA);
        //mostramos la pantalla con cliente logeado
        pantallaTransferencias.setVisible(true);

    }//GEN-LAST:event_btnTrasferenciasActionPerformed

    private void btnRetiroSinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroSinCuentaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(this,"Se generara un folio, porfavor espere");
    }//GEN-LAST:event_btnRetiroSinCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrearMasCuentas;
    private javax.swing.JButton btnMisCuentas;
    private javax.swing.JButton btnRetiroSinCuenta;
    private javax.swing.JButton btnTrasferencias;
    // End of variables declaration//GEN-END:variables
}